In [11]:
import numpy as np
print("ones", np.ones(5))
print("arange", np.arange(5))
print("linspace", np.linspace(0., 17., 5))  # 0-1 사이의 균일한 간격의 5개 숫자
print("random", np.random.uniform(size=7))  # 7개의 랜덤값
print("custom", np.array([2,3,5]))  # 파이썬의 list나 tuple을 받아서 NumPy 배열로 바꿔준다. 


ones [ 1.  1.  1.  1.  1.]
arange [0 1 2 3 4]
linspace [  0.     4.25   8.5   12.75  17.  ]
random [ 0.1014485   0.16516826  0.91629606  0.49931738  0.22687757  0.52336433
  0.24766253]
custom [2 3 5]


In [12]:
np.ones(5, dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [13]:
np.arange(5).astype(np.float64)

array([ 0.,  1.,  2.,  3.,  4.])

In [8]:
np.array([[1,2], [3,4], [5,6]])

array([[1, 2],
       [3, 4],
       [5, 6]])